### ISSUE TITLE
Find best solution for naming convention

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/FluentLayout#1]
```csharp
public static TBindable BindText<TBindable>(this TBindable self) where TBindable : Label
```
```csharp
public static TBindable BindText<TBindable>(this TBindable self) where TBindable : Button
```
This example don't work due these two methods the same from signature point of view and cause compiler error.

Need to find approach, how to handle such cases

1) BindTextLabe BindTextButton
2) BindText1 BindText2
3) Bind().Text().Build() 
etc.

**Comment by AndreiMisiukevich** [comment]
Maybe

```csharp
new Label()
.As<Label>()
.BindText(...)
.PutTextColor(...)
.SetAbsoluteLayoutBounds(...)
.End();
```

**Comment by Miiite** [comment]
Feels weird to have to call "As<Label>" on something you explicitely created as being a "new Label()"

**Comment by AndreiMisiukevich** [comment]
@Miiite hm.. maybe it would make sense to remove generics.

```csharp
new Label().BindText(...);
new CustomLabel().BindText(...).As<CustomLabel>() // in case if you really need to preserve this type for future
```

**Comment by Miiite** [comment]
What about using only one generic method like
`public static TBindable BindText<TBindable>(this TBindable self) where TBindable : View`

and inside the body of the method, figure out what kind of view it really is. Then raise a NotSupportedException if we are trying to create a TextBinding on something that does not support it
